name: gym_cronometro
description: "Gym rest timer with sets counter."
publish_to: 'none'
version: 1.0.0+1
# author: Arthur Bolsoni <arthurbolsoni@gmail.com>

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  vibration: ^3.1.8
  flutter_local_notifications: ^20.0.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
